### ISSUE TITLE
Failed to withdrawl from OKX to LNbits Infinity

### ISSUE THREAD

**Issue by btctodamun** [lnbits/lnbits-infinity#8]
I used LNbits Infinity for the first time, and I created two invoices. One is 5 million sats and the other is 1 million sats.
![179139244-308c63d9-75cb-4331-ae2d-f7fd3b682ad3](https://user-images.githubusercontent.com/109325603/179339192-9677bf71-3928-4997-a4e2-2c9f79d5b178.png)
![179139228-82f28856-6298-4233-a55e-99c8ba791202](https://user-images.githubusercontent.com/109325603/179339195-4c84a55d-0e02-4b48-a5d0-eb13e1d5c3dc.png)

Then I launched two withdrawl from OKX. As you can see those two were complete.
![179140949-1d338a92-9965-4bdf-a1bc-00195349696a](https://user-images.githubusercontent.com/109325603/179339203-d57a9731-c155-43b1-ac25-9b74004988ab.jpg)
![179140957-148ce5fe-ee13-4641-b3cc-70c32e830316](https://user-images.githubusercontent.com/109325603/179339204-d5fb2729-d87a-48c8-8b72-635f8c28a80e.jpg)

But my LNbits Infinity didn't receive any of sats at all.
![179141423-d0f9b60b-451d-4bd2-9f3f-a088da31e4db](https://user-images.githubusercontent.com/109325603/179339209-9473b936-7eff-4af1-9d31-4d05832e9fbd.png)
![Uploading 179141413-bd413bce-1c64-4254-9396-ca21cf5575e2.png…]()

I had a contact with OKX, they replied that they did send those sats, so what's the problem?
P.S. I did another one withdrawl from OKX to LNbits legend and it worked. So what's the problem with OKX-to-LNbits.Infinity route?

**Comment by fiatjaf** [comment]
You did that on https://infinity.lnbits.com? Can you paste the hash here as text?

**Comment by btctodamun** [comment]
Yes, I did that on https://infinity.lnbits.com/.
here are those hash:
81c8a1906914c98bae7d32b054dcc77cf61c6bbfd25c60213bef41e214f7a7c5
6c3b776d98c3700f0257387500da692c6b7b6429272c84fe8c8c1d297705234e

**Comment by fiatjaf** [comment]
Check now if it is there please.

**Comment by btctodamun** [comment]
I just checked it, as you can see in my screenshots, there are still no sats.
![b05238a8-69ae-47f5-83c1-5fcf47a60b67](https://user-images.githubusercontent.com/109325603/179358007-a8fbd255-eec1-4ae4-965d-518382d9aa48.jpg)
![1f49c659-683b-431a-bfc8-d367916b1a74](https://user-images.githubusercontent.com/109325603/179358010-c162674c-b5f1-40ad-84a4-907245c0e570.jpg)

**Comment by fiatjaf** [comment]
Done.

**Comment by btctodamun** [comment]
I hate to say it, but my funds are still not there, the invoices are still pending, but if you use another lighting wallet to scan it, it shows "expired".
I still haven't got my bitcoin, where exactly it is? It feels bad losing 6 million sats, I thought I did every step right :( and I still don't know what's the reason cause it.

![637ffc0c-92e1-4c97-9523-33c4eaff42c7](https://user-images.githubusercontent.com/109325603/179380497-fceeddfc-22ac-4dea-8dfd-8dd8ed41d4af.jpg)

**Comment by btctodamun** [comment]
And another question: Did OKX really send those sats? If OKX did send them, did LNbits.Infinity receive those sats? If LNbits.Infinity did receive, so where are those 6 million sats?
@fiatjaf Looking forward your reply, please, it means a lot to me.

**Comment by fiatjaf** [comment]
The sats are there, yes, and the invoices are not pending anymore. I checked.

But now you're saying that, so I am confused. Will check again.

**Comment by btctodamun** [comment]
So, in my point of view, this is maybe a UI bug or what? It's weird.

**Comment by fiatjaf** [comment]
The confusion was on my side. Now it should be working.

**Comment by btctodamun** [comment]
Thanks a lot, now it's done.
![20220719095933](https://user-images.githubusercontent.com/109325603/179650434-ff5f09d8-ba56-4e5b-9834-2a2afecb6dcd.png)
.

**Comment by btctodamun** [comment]
It kills me now, today I meet a new problem. When I use LNbits.Infinity to send funds to Wallet of Satoshi, one particular transaction was made, and my sats did decrease, but Wallet of Satoshi didn’t receive that fund.
![AA74445D-84DC-467B-A03F-B7899F0244A5](https://user-images.githubusercontent.com/109325603/179753412-2f215d72-87ec-470e-9c9c-ea60e3bc92e3.png)
![50DD8B48-A9CA-44BA-9789-0C2BC11ED1A1](https://user-images.githubusercontent.com/109325603/179753437-d05c3d24-1983-43b6-972e-a89fb3d9f0af.png)
Here is the hash: 
22ba2cb0b4f2086a7c8ea29bd1a6a9cda8fd1a8aa8deae81041c127aa7b3c043
@fiatjaf

**Comment by btctodamun** [comment]
Plus, a little problem, these two transactions were send successfully, but the display was not correct.
![EAE21771-160B-4087-BF70-19BAFF0A9064](https://user-images.githubusercontent.com/109325603/179756963-9cd89c7e-cf8b-4d65-9ad4-538d45792203.jpeg)

**Comment by fiatjaf** [comment]
I've fixed a bunch of things again.

Can you check now again if everything is looking fine?

**Comment by btctodamun** [comment]
Nice talking to you again.

In my perspective of view from the user interface tells me: a fixed and an unfixed.

First: “received” and “sent” icons are now displaying rightly.

![6F08BBD6-A96D-4177-BE10-A389470A2F60](https://user-images.githubusercontent.com/109325603/180335427-9925a9d6-fc7f-42e4-a555-ea003350aa81.jpeg)

![28E764A9-7432-4AD9-8EC1-6BDAA020D5D7](https://user-images.githubusercontent.com/109325603/180335438-e759ecb8-8bfd-4719-b241-367e8b332b7d.jpeg)

Second: a particular large-amount payment is still facing a problem, in the meantime, the display of balance is not showing the right number.
![542DDC9A-E273-4536-BC9D-EF6449A294FD](https://user-images.githubusercontent.com/109325603/180336238-6cd637d1-1724-4a73-9602-072e6d347ca7.jpeg)
![568FCB0F-FA00-40C7-856B-262AFC9045FC](https://user-images.githubusercontent.com/109325603/180336249-f5652564-1386-46f3-9d93-b3571c161974.jpeg)

Now I paste the unfixed-payment invoice QR code and text:
![9CA635D2-BE93-48C4-A9A9-3BC78440D435](https://user-images.githubusercontent.com/109325603/180336436-865a1902-d049-4009-ab9a-2ee25f19e61d.png)
22ba2cb0b4f2086a7c8ea29bd1a6a9cda8fd1a8aa8deae81041c127aa7b3c043

Thanks for your fixing and replying!

**Comment by fiatjaf** [comment]
Thank you for your patience and for your very informative screenshots.
